on:
  workflow_dispatch:

jobs:
  release: 
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # Ajuste para a versão do Node.js que você está utilizando
      - run: npm ci
      - run: npm run build
      - name: Add .npmignore
        run: echo "noop.js" >> .npmignore
      - name: Install Semantic Release
        run: npm install -g semantic-release@17 @semantic-release/changelog@5 @semantic-release/git@9
      - name: Semantic Release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
